---
- name: fail if noc is not selected
  fail:
    msg: "Metrics role have to be set with noc role to get own sources."
  when:
    - has_svc_metrics is defined
    - has_svc_noc is not defined
  tags:
    - checks

- name: No metrics service is set
  fail:
    msg: "No metrics service is set. Please setup at least one. "
  when: "'svc-metrics-exec' not in groups"
  tags:
    - checks
