---
- name: Install RedOS system packages 2/2
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: "True"
  vars:
    packages:
      - git
      - patch
      - python-virtualenv
      - gcc
      - libffi
      - libffi-devel
      - libmemcached
      - libmemcached-devel
      - zlib-devel
      - jemalloc
      - bzip2
      - cmake
      - openssl-devel
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"
  tags:
    - requirements

- name: Install RedOS system packages for python3
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - python3
      - python3-devel
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"

- name: Install supervisord init script
  template:
    src: "noc.service.j2"
    dest: "/etc/systemd/system/{{ noc_system_service }}.service"
    mode: "a+r"
  notify: reload systemd
