---
- name: Install smilint/smidump packages
  yum:
    name: "{{ packages }}"
    update_cache: "True"
  vars:
    packages:
      - libsmi
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"
  tags:
    - requirements
