---
- block:

    - name: count servers
      set_fact:
        redpanda_servers_count: "{{ groups['svc-redpanda-exec'] | length }}"

    - name: Ensure redpanda setup. max server count
      fail:
        msg: |
          Redpanda servers have to be set up on 1,3 or 5 nodes. less is better. Current count is {{ redpanda_servers_count }}
      when: redpanda_servers_count | int not in [1,3,5]

  when:
    - has_svc_redpanda is defined
  tags:
    - checks
