---
- name: Place redpanda config
  template:
    src: "redpanda_config.yml.j2"
    dest: "{{ redpanda_config_path }}/redpanda.yml"
    owner: "{{ redpanda_user }}"
    group: "{{ redpanda_group }}"
  notify:
    - restart redpanda
  tags:
    - config
