---
- name: Create redpanda directories
  file:
    dest: "{{ item }}"
    state: directory
    owner: "{{ redpanda_user }}"
    group: "{{ redpanda_group }}"
  with_items:
    - "{{ redpanda_config_path }}"
    - "{{ redpanda_data_directory }}"
