---
- name: "Include OS-specific tasks"
  include_tasks: "os/{{ ansible_distribution }}_{{ ansible_distribution_major_version }}/main.yml"
  tags:
    - requirements
    - config

- name: Redpanda config
  import_tasks: config.yml
  tags:
    - config

- name: start Redpanda
  systemd:
    name: redpanda
    enabled: true
    state: started

- name: call consul to setup redpanda
  run_once: true
  include_role:
    name: consul
    tasks_from: service_config_set
  vars:
    consul_service_key: "noc/msgstream/client_class"
    consul_service_value: "noc.core.msgstream.redpanda.RedPandaClient"
    consul_service_token: None
  when:
    - "'consul://' in config_order"

- block:

    - name: Ensure settings.yml is exists
      file:
        path: "{{ noc_root }}/etc/settings.yml"
        state: touch
        owner: root
      delegate_to: "{{ item }}"
      with_items: "{{ groups['svc-noc-exec'] }}"

    - name: Edit settings.yml for redpanda's configuration
      yedit:
        src: "{{ noc_root }}/etc/settings.yml"
        state: present
        edits:
          - key: noc.msgstream.client_class
            value: "noc.core.msgstream.redpanda.RedPandaClient"
      delegate_to: "{{ item }}"
      with_items: "{{ groups['svc-noc-exec'] }}"

  when:
    - "'consul://' not in config_order"
  tags:
    - config

- name: Place redpanda consul check
  import_role:
    name: consul
    tasks_from: service
  vars:
    consul_service_name: redpanda
    consul_service_tags: ""
    consul_service_port: "9292"
    consul_service_check_type: "tcp"
    consul_service_check_value: "{{ ansible_host }}:{{ redpanda_kafka_port }}"
    consul_service_check_interval: "10s"
    consul_service_check_http_skip_verify: "False"
