---
- name: "Include OS-specific tasks"
  include_tasks: "os/{{ ansible_distribution }}_{{ ansible_distribution_major_version }}/main.yml"
  tags:
    - requirements
    - config

- name: Redpanda config
  import_tasks: config.yml
  tags:
    - config

- name: start Redpanda
  systemd:
    name: redpanda
    enabled: true
    state: started

- name: call consul to setup redpanda
  run_once: true
  include_role:
    name: consul
    tasks_from: service_config_set
  vars:
    consul_service_key: "noc/msgstream/client_class"
    consul_service_value: "noc.core.msgstream.redpanda.RedPandaClient"
    consul_service_token: None
  when:
    - "'consul://' in config_order"
