---
- name: Add redpanda user
  user:
    name: "{{ redpanda_user }}"
    comment: "redpanda user"
    group: "{{ redpanda_group }}"
    system: "True"
    home: "{{ redpanda_home_dir }}"
    shell: "{{ fake_shell }}"
  tags:
    - config

- name: "Include OS-specific tasks"
  include_tasks: "os/{{ ansible_distribution }}_{{ ansible_distribution_major_version }}/main.yml"
  tags:
    - requirements
    - config

- name: Redpanda config
  import_tasks: config.yml
  tags:
    - config

- name: Redpanda config
  import_tasks: dirs.yml
  tags:
    - config

- name: start Redpanda
  systemd:
    name: redpanda
    enabled: true
    state: started

- name: call consul to setup redpanda
  run_once: true
  include_role:
    name: consul
    tasks_from: service_config_set
  vars:
    consul_service_key: "noc/msgstream/client_class"
    consul_service_value: "noc.core.msgstream.redpanda.RedPandaClient"
    consul_service_token: None
  when:
    - "'consul://' in config_order"  #Look in noc/tasks/config.yml for local file configuration

- name: Place redpanda consul check
  import_role:
    name: consul
    tasks_from: service
  vars:
    consul_service_name: redpanda
    consul_service_tags: ""
    consul_service_port: "{{ redpanda_kafka_port }}"
    consul_service_check_type: "tcp"
    consul_service_check_value: "{{ ansible_host }}:{{ redpanda_kafka_port }}"
    consul_service_check_interval: "10s"
    consul_service_check_http_skip_verify: "False"
