---
# File: dirs.yml - Directory settings

- name: Create directories
  file:
    dest: "{{ item }}"
    state: directory
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
  with_items:
    - /var/consul
    - /var/run/consul
    - "{{ consul_configd_path }}"
    - "{{ consul_scripts_path }}"
