---
- name: Redpanda tasks
  hosts: svc-redpanda-exec
  become: "True"
  any_errors_fatal: "False"
  gather_facts: "True"
  tags:
    - redpanda
  vars_files:
    - "../../vars/main.yml"
    - "../../vars/{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
    - "vars/{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
  roles:
    - role: redpanda
    - role: goss
      tags: [goss]
      vars:
        goss_service_name: redpanda
  post_tasks:
    - name: set redpanda complete
      set_fact:
        redpanda_complete: "True"
