---
- block:

    - name: Role nsqlookupd is not needed anymore
      msg: 'Uncheck all "nsqlookupd" roles in Tower at Services section'
      when:
        - nsqlookupd_removed is defined and nsqlookupd_removed

  when:
    - has_svc_nsqlookupd is defined
  tags:
    - tests
