variables:
  REG_NAME: registry.getnoc.com
  S3_BASE: https://s3.getnoc.com
  S3_BUCKET: $CI_PROJECT_NAMESPACE

stages:
  - test
  - build
  - upload

test:empty:
  stage: test
  image: registry.getnoc.com/noc/nocmc/feature_microservices:dev
  variables:
    NOC_PG_DB: noc
    NOC_PG_USER: noc
    NOC_PG_PASSWORD: noc
  services:
    - name: registry.getnoc.com/infrastructure/postgres:master
      alias: postgres 
    - name: registry.getnoc.com/infrastructure/mongo:master
      alias: mongo
  script:
    - export NOC_PG_ADDRESSES=registry.getnoc.com-infrastructure-postgres:5432
    - export NOC_MONGO_ADDRESSES=registry.getnoc.com-infrastructure-mongo:27017
    - mkdir /opt/noc/collections
    - mv src/* /opt/noc/collections
    - ls /opt/noc/collections
    - cd /opt/noc
    - python manage.py syncdb --noinput
    - python manage.py migrate
    - python commands/collection.py sync
  tags:
    - docker

test:with data:
  stage: test
  image: registry.getnoc.com/noc/nocmc/feature_microservices:dev
  variables:
    NOC_PG_DB: noc
    NOC_PG_USER: noc
    NOC_PG_PASSWORD: noc
  services:
    - name: registry.getnoc.com/infrastructure/postgres:dev
      alias: postgres 
    - name: registry.getnoc.com/infrastructure/mongo:dev
      alias: mongo
  script:
    - export NOC_PG_ADDRESSES=registry.getnoc.com-infrastructure-postgres:5432
    - export NOC_MONGO_ADDRESSES=registry.getnoc.com-infrastructure-mongo:27017
    - mkdir /opt/noc/collections
    - mv src/* /opt/noc/collections
    - ls /opt/noc/collections
    - cd /opt/noc
    - python manage.py migrate
    - python commands/collection.py sync
  tags:
    - docker

build:
  stage: build
  image: python:2.7-alpine
  script:
    - mkdir -p dist 
    - ./build.py package.json
    - echo ${CI_BUILD_REF} > dist/collections.latest
  tags:
    - docker
  artifacts:
    paths:
      - dist/
    expire_in: 3 min
  only:
    - moversion@noc/collections
    - master@noc/collections

upload:
  stage: upload 
  image: registry.getnoc.com/infrastructure/s3helper:master
  script:
    /tmp/mc -q cp dist/* cdn/$S3_BUCKET/
  tags:
    - docker 
  only:
    - moversion@noc/collections
    - master@noc/collections
