variables:
  REG_NAME: registry.getnoc.com
  S3_BASE: https://s3.getnoc.com
  S3_BUCKET: $CI_PROJECT_NAMESPACE

stages:
  - test
  - build
  - upload

build:
  stage: build
  image: python:2.7-alpine
  script:
    - mkdir -p dist 
    - ./build.py package.json
    - echo ${CI_BUILD_REF} > dist/collections.latest
  tags:
    - docker
  artifacts:
    paths:
      - dist/
    expire_in: 3 min
  only:
    - master@noc/collections

test:empty:
  stage: test
  image: registry.getnoc.com/noc/noc-docker:dev
  variables:
    NOC_PG_DB: noc
    NOC_PG_USER: noc
    NOC_PG_PASSWORD: noc
  services:
    - registry.getnoc.com/infrastructure/postgres:master
    - registry.getnoc.com/infrastructure/mongo:master
  script:
    - export NOC_PG_HOST=$(env | grep REGISTRY.GETNOC.COM_INFRASTRUCTURE_POSTGRES_PORT_5432_TCP_ADDR | awk -F '=' '{print $2}')
    - export NOC_MONGO_HOST=$(env | grep REGISTRY.GETNOC.COM_INFRASTRUCTURE_MONGO_PORT_27017_TCP_ADDR | awk -F '=' '{print $2}')
    - mkdir /opt/noc/collections
    - mv src/* /opt/noc/collections
    - ls /opt/noc/collections
    - cd /opt/noc
    - ./noc migrate
    - ./noc collection sync
  tags:
    - docker

test:with data:
  stage: test
  image: registry.getnoc.com/noc/noc-docker:dev
  variables:
    NOC_PG_DB: noc
    NOC_PG_USER: noc
    NOC_PG_PASSWORD: noc
  services:
    - registry.getnoc.com/infrastructure/postgres:dev
    - registry.getnoc.com/infrastructure/mongo:dev
  script:
    - export NOC_PG_HOST=$(env | grep REGISTRY.GETNOC.COM_INFRASTRUCTURE_POSTGRES_PORT_5432_TCP_ADDR | awk -F '=' '{print $2}')
    - export NOC_MONGO_HOST=$(env | grep REGISTRY.GETNOC.COM_INFRASTRUCTURE_MONGO_PORT_27017_TCP_ADDR | awk -F '=' '{print $2}')
    - mkdir /opt/noc/collections
    - mv src/* /opt/noc/collections
    - ls /opt/noc/collections
    - cd /opt/noc
    - ./noc migrate
    - ./noc collection sync
    - ./noc verify-model
  tags:
    - docker

upload:
  stage: upload 
  image: registry.getnoc.com/infrastructure/s3helper:master
  script:
    /tmp/mc -q cp dist/* cdn/$S3_BUCKET/
  tags:
    - docker 
  only:
    - master@noc/collections