variables:
  REG_NAME: registry.getnoc.com
  S3_BASE: https://s3.getnoc.com
  S3_BUCKET: $CI_PROJECT_NAMESPACE

stages:
  - build
  - test
  - upload

build:
  stage: build
  image: python:2.7-alpine
  script:
    - mkdir -p dist 
    - ./build.py package.json
    - echo ${CI_BUILD_REF} > dist/collections.latest
  tags:
    - docker
  artifacts:
    paths:
      - dist/
    expire_in: 3 min

test:empty:
  stage: test
  image: registry.getnoc.com/noc/noc-docker:master
  variables:
    NOC_PG_DB: noc
    NOC_PG_USER: noc
    NOC_PG_PASSWORD: noc
  services:
    - registry.getnoc.com/infrastructure/postgres:master
    - registry.getnoc.com/infrastructure/mongo:master
  script:
    - mount 
    - ls -lah .
    - ./bin/python ./noc migrate
    - ./scripts/deploy/install-packages requirements/collections.json
    - ./noc collection sync
  tags:
    - docker

upload:
  stage: upload 
  image: registry.getnoc.com/infrastructure/s3helper:master
  script:
    /tmp/mc -q cp dist/* cdn/$S3_BUCKET/
  tags:
    - docker 
