---
- name: fail if noc is not selected
  fail:
    msg: "UI role have to be set with noc role to get own sources."
  when:
    - has_svc_ui is defined
    - has_svc_noc is not defined
  tags:
    - checks
