---
- name: Compile bytecode
  command: ./scripts/deploy/compile-bytecode
  args:
    chdir: "{{ noc_root }}"
  register: result
  changed_when: "'CHANGED' in result.stdout"
  failed_when: "'ERROR' in result.stdout"
  environment:
    NOC_CONFIG: "{{ config_order }}"

- name: Compiling binary modules
  command: ./scripts/deploy/cythonize
  args:
    chdir: "{{ noc_root }}"
  register: result
  changed_when: "'CHANGED' in result.stdout"
  failed_when: "'ERROR' in result.stdout"
  environment:
    NOC_CONFIG: "{{ config_order }}"
  tags:
    - requirements
    - get_source

- name: "Downloading rust libs"
  get_url:
    url: "https://cdn.getnoc.com/noc/libs/libip.so"
    dest: "{{ noc_root }}/speedup/ip.so"
    force: true
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"
  register: rustipso

- block:
    - name: Find old ip.c files
      find:
        paths: "{{ noc_root }}/speedup"
        patterns: "^ip.c.*"
        use_regex: true
      register: ipc_to_delete

    - name: Remove files
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ ipc_to_delete.files }}"
  when: rustipso.changed

- name: Cleanup hanging .pyc files
  command: ./scripts/deploy/cleanup-pyc
  args:
    chdir: "{{ noc_root }}"
  register: result
  changed_when: "'CHANGED' in result.stdout"
  failed_when: "'ERROR' in result.stdout"
  environment:
    NOC_CONFIG: "{{ config_order }}"
    NOC_PG_ADDRESSES: postgres:5432
  tags:
    - get_source
