---
- name: Remove {{ ct_service_name }} template
  file:
    state: absent
    path: '{{ consul_template_templates_dir }}/{{ ct_service_source.split(".")[-1] }}'
  when: not ct_service_source_template | bool
  notify:
    - reload consul-template

- name: Remove {{ ct_service_name }} template
  file:
    state: absent
    path: '{{ consul_template_templates_dir }}/{{ ct_service_source.split(".")[-1] }}'
  when: ct_service_source_template | bool
  notify:
    - reload consul-template

- name: Remove template for {{ ct_service_name }}
  file:
    state: absent
    path: "{{ consul_template_config_dir }}/{{ ct_service_name }}.conf"
  notify:
    - reload consul-template
