---
- name: Get Consul-template package checksum file
  get_url:
    url: "{{ consul_template_checksum_file_url }}"
    dest: "{{ consul_template_temp_file_checksum }}"
    validate_certs: "True"
  delegate_to: 127.0.0.1
  become: "False"
  run_once: "True"
  environment:
    https_proxy: "{{ http_proxy }}"
  when: not consul_template_own_install

- name: Get Consul-template package checksum
  command: "grep {{ consul_template_pkg }} {{ consul_template_temp_file_checksum }}"
  check_mode: "False"
  register: consul_sha256
  delegate_to: 127.0.0.1
  become: "False"
  run_once: "True"
  changed_when: false
  when: not consul_template_own_install

- name: Download Consul-template
  get_url:
    url: "{{ consul_template_zip_url }}"
    dest: "{{ consul_template_temp_file }}"
    checksum: "sha256:{{ consul_sha256.stdout.split(' ')|first }}"
    timeout: 42
    validate_certs: "True"
  delegate_to: 127.0.0.1
  become: "False"
  run_once: "True"
  environment:
    https_proxy: "{{ http_proxy }}"
  when: not consul_template_own_install

- name: create consul-template tmp dir
  file:
    dest: "{{ consul_template_temp_unarchive }}"
    state: directory
  when: not ansible_check_mode

- name: Unarchive Consul-template and install binary
  unarchive:
    src: "{{ consul_template_temp_file }}"
    dest: "{{ consul_template_temp_unarchive }}"
    owner: "{{ consul_template_user }}"
    group: "{{ consul_template_group }}"
    mode: 0755
    creates: "{{ consul_template_temp_unarchive }}/{{ consul_template_binary }}"
  when: not ansible_check_mode and not consul_template_own_install
  register: ct_archive_extracted

- name: Overwrite Consul-template binary if needed
  copy:
    src: "{{ consul_template_temp_unarchive }}/{{ consul_template_binary }}"
    dest: "{{ consul_template_bin_path }}/{{ consul_template_binary }}"
    remote_src: "True"
    mode: 0755
  when:
    - ct_archive_extracted is changed
    - not ansible_check_mode
  notify:
    - restart consul-template
