---
- name: Remove nsqd group
  group:
    name: nsq
    state: absent

- name: Remove nsqd user
  user:
    name: nsq
    shell: "{{ fake_shell }}"
    state: absent

- name: Remove path for on-disk queue files
  file:
    path: "{{ item.dir }}"
    state: absent
  with_items:
    - dir: "{{ nsqd_db_dir }}"
      mode: "0770"
    - dir: "{{ nsqd_config_dir }}"
      mode: "u=rwx,g=rx,o=rx"
    - dir: "{{ nsq_root }}"
      mode: "u=rwx,g=rx,o=rx"

- name: remove nsqd ct template
  import_role:
    name: consul-template
    tasks_from: deservice
  vars:
    ct_service_name: nsqd
    ct_service_source: "nsqd.conf.ctmpl"
    ct_service_dest: "{{ nsqd_config_dir }}/nsqd.conf"
    ct_service_command: "{{ reload_command }}"
    ct_service_command_timeout: "60s"
    ct_service_source_template: "True"

- name: Disable nsq system service
  service:
    name: "nsqd"
    enabled: "False"
    state: stopped

- name: Delete all nsqd consul checks
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - path: "{{ consul_configd_path }}/nsqd.json"
    - path: "{{ consul_configd_path }}/nsqdhttp.json"


- name: set nsqd removed flag
  set_fact:
    nsqd_removed: "True"
