---
- name: Add CH repository
  shell: yum-config-manager --add-repo=https://packages.clickhouse.com/rpm/clickhouse.repo
  args:
    creates: /etc/yum.repos.d/clickhouse.repo
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"

- name: Install CH
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: "True"
  vars:
    packages:
      - "clickhouse-client-{{ clickhouse_version }}"
      - "clickhouse-server-{{ clickhouse_version }}"
      - "clickhouse-common-static-{{ clickhouse_version }}"
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"
  tags:
    - requirements
