---
- name: fail if noc is not selected
  fail:
    msg: "Mailsender role have to be set with noc role to get own sources."
  when:
    - has_svc_mailsender is defined
    - has_svc_noc is not defined
  tags:
    - checks

- name: fail if "mx" is not selected
  fail:
    msg: "Mailsender service works with 'mx' service. Please setup at least one somewhere."
  when:
    - has_svc_mailsender is defined
    - "'svc-mx-exec' not in groups"
  tags:
    - checks
