---
# mongodb_replicaset is not idempotent. first init have to be done without login user and password
# second and further with it.
# let it live here for some time
# TODO REMOVE ME after 1 jan 2022

- name: Install pymongo
  pip:
    name: "pymongo=={{ pymongo_version }}"
    virtualenv: "{{ mongo_control_venv }}"
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"
  tags:
    - requirements

#- name: Ansible full of bugs
#  set_fact:
#    ansible_correct_python: "{{ ansible_python_interpreter }}"
#    ansible_python_interpreter: "{{ mongo_control_venv }}/bin/python"

- name: create rs
  mongodb_replicaset:
    members: "{{ ansible_hostname }}"
    replica_set: "{{ mongod_rs }}"
    state: present
    login_user:
    login_password:
    login_database: "admin"
    validate: no
  vars:
    ansible_python_interpreter: "{{ mongo_control_venv }}/bin/python"
  register: rs_status

- block:
    - name: Create admin user configuration script
      template:
        src: admininit.js.j2
        dest: "{{ mongo_dir }}/admininit.js"
      no_log: "{{ tower_show_secrets }}"
      tags:
        - config

    - name: sleep while mongodb electing primary
      pause:
        seconds: 5

    - name: Create admin user
      command: "{{ mongo_path }} admin {{ mongo_dir }}/admininit.js"
  when: rs_status is changed

- name: create noc user
  mongodb_user:
    login_user: "{{ noc_mongo_admin_user }}"
    login_password: "{{ mongod_password }}"
    login_database: admin
    database: "{{ mongod_db }}"
    name: "{{ mongod_user }}"
    password: "{{ mongod_password }}"
    replica_set: "{{ mongod_rs }}"
    roles:
      - db: "{{ mongod_db }}"
        role: dbOwner
    state: present
    vars:
      ansible_python_interpreter: "{{ mongo_control_venv }}/bin/python"

#- name: Ansible full of bugs 2
#  set_fact:
#    ansible_python_interpreter: "{{ ansible_correct_python }}"
