---
- name: reload systemd
  become: "True"
  systemd:
    name: "{{ mongod_system_service }}"
    daemon_reload: "True"

- name: restart mongod
  become: "True"
  service:
    name: "{{ mongod_system_service }}"
    state: restarted
