---
- name: fail if noc is not selected
  fail:
    msg: "Worker role have to be set with noc role to get own sources."
  when:
    - has_svc_worker is defined
    - has_svc_noc is not defined
  tags:
    - checks

- name: No worker service is set
  fail:
    msg: "No worker service is set. Please setup at least one. "
  when: "'svc-worker-exec' not in groups"
  tags:
    - checks