---
listen: 0.0.0.0:9292
host: liftbridge
nats:
  servers:
    - nats://nats:4222/
logging:
  level: info
  raft: true
streams:
    compact.enabled: false
    retention.max:
        age: 3h
    segment.max:
        age: 20m
cursors:
    stream.auto.pause.time: 0
    stream.partitions: 1
