---
- name: add the redpanda repo
  yum_repository:
    name: redpanda
    description: redpanda yum repo
    gpgkey: "https://packages.vectorized.io/nzc4ZYQK3WRGd9sy/redpanda/gpg.988A7B0A4918BC85.key"
    baseurl: https://packages.vectorized.io/nzc4ZYQK3WRGd9sy/redpanda/rpm/el/7/$basearch
    state: present
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"

- name: install redpanda from repository
  yum:
    name: "redpanda-{{ redpanda_version }}"
    state: present
    update_cache: true
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"

- name: set data dir file perms
  file:
    path: "{{ redpanda_data_directory }}"
    owner: redpanda
    group: redpanda
