---
- name: Fail if PostgreSQL version is not equal to "{{ postgres_version }}"
  fail:
    msg: Only "{{ postgres_version }}" version of PostgreSQL is supported now
  when:
    - postgres_version is version_compare("{{ postgres_version }}", '<>')
