---
- name: add the redpanda repo
  shell: |
    curl -1sLf https://packages.vectorized.io/sMIXnoa7DK12JW4A/redpanda/cfg/setup/bash.deb.sh | sudo -E bash
  args:
    warn: false
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"

- name: install redpanda from repository
  apt:
    name: redpanda
    state: present
    update_cache: true
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"

- name: set data dir file perms
  file:
    path: "{{ redpanda_path_data }}"
    owner: redpanda
    group: redpanda
