---
- name: Add Grafana repository
  yum_repository:
    name: grafana
    description: Grafana repository
    baseurl: https://packages.grafana.com/oss/rpm
    gpgcheck: "True"
    gpgkey: https://packages.grafana.com/gpg.key
    enabled: "True"
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"
  when: not grafana_own_install
  tags:
    - repo

- name: Install Grafana
  yum:
    name:
      - grafana{{ '-'+grafana_version if not grafana_own_install else '' }}
      - open-sans-fonts
    state: present
    update_cache: "True"
    allow_downgrade: "True"
  tags:
    - requirements
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"
