---
- name: Install Nginx
  dnf:
    name: nginx
    state: present
    update_cache: "False"
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"
  tags:
    - requirements

- name: Enable Nginx system service
  service:
    name: "{{ nginx_system_service }}"
    enabled: "True"
    state: started
  notify: reload nginx

- name: Remove default.conf site
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify: reload nginx

- include_tasks: "firewall.yml"
  when: (nginx_permit_firewall)
  tags:
    - firewall
