---
- name: add the redpanda repo
  shell: |
    curl -1sLf https://packages.vectorized.io/sMIXnoa7DK12JW4A/redpanda/cfg/setup/bash.rpm.sh | sudo -E bash
  args:
    warn: false

- name: install redpanda from repository
  package:
    name:
      - redpanda
    state: present
    update_cache: true

- name: set data dir file perms
  file:
    path: "{{ redpanda_path_data }}"
    owner: redpanda
    group: redpanda
