version: "2"
services:
  shell:
    image: "registry.getnoc.com/infrastructure/docs:master"
    restart: "no"
    working_dir: /noc
    environment:
      NOC_SRC_PATH: /noc
    volumes:
      - $PWD:/noc

  html-en:
    image: "registry.getnoc.com/infrastructure/docs:master"
    restart: "no"
    volumes:
      - $PWD:/noc
    environment:
      NOC_SRC_PATH: /noc
    working_dir: /noc
    command: > 
      sh -c "mkdir -p docs/src/en/src build/docs/en 
             && sphinx-build -a -E -j auto -b html docs/src/en build/docs/en"

  html-en-inc:
    image: "registry.getnoc.com/infrastructure/docs:master"
    restart: "no"
    volumes:
      - .:/docs
    working_dir: /docs
    command: sphinx-build -b html src/en build/en

  html:
    depends_on:
      - html-en
    image: "registry.getnoc.com/infrastructure/docs:master"
    restart: "no"
    volumes:
      - .:/docs
    working_dir: /docs
    command: /bin/true

  epub-en:
    image: "registry.getnoc.com/infrastructure/docs:master"
    restart: "no"
    volumes:
      - .:/docs
    working_dir: /docs
    command: sphinx-build -b epub src/en build/epub/en

  epub:
    depends_on:
      - epub-en
    image: "registry.getnoc.com/infrastructure/docs:master"
    restart: "no"
    volumes:
      - .:/docs
    working_dir: /docs
    command: /bin/true

  build:
    depends_on:
      - html
      - epub
    image: "registry.getnoc.com/infrastructure/docs:master"
    restart: "no"
    volumes:
      - .:/docs
    working_dir: /docs
    command: /bin/true

  serve:
    image: "nginx:mainline"
    restart: "no"
    volumes:
      - ./build/:/usr/share/nginx/html
    ports:
      - 48888:80
