version: "3.4"
services:
  mkdocs-serve-ru:
    image: "registry.getnoc.com/infrastructure/mkdocs:master"
    restart: "no"
    working_dir: /opt/noc
    volumes:
      - $PWD/..:/opt/noc
    command: mkdocs serve --dirtyreload -a 0.0.0.0:8000 --config-file=/opt/noc/docs/ru/mkdocs.yml
    ports:
      - "8081:8000"
#    network_mode: "host"

  mkdocs-serve-en:
    image: "registry.getnoc.com/infrastructure/mkdocs:master"
    restart: "no"
    working_dir: /opt/noc
    volumes:
      - $PWD/..:/opt/noc
    command: mkdocs serve --dirtyreload -a 0.0.0.0:8000 --config-file=/opt/noc/docs/en/mkdocs.yml
    ports:
      - "8082:8000"
#    network_mode: "host"
  
