---
- name: "Install Grafana plugin"
  grafana_plugin:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: present
    grafana_plugins_dir: "{{ grafana_plugins_dir }}"
  with_items:
    - name: simpod-json-datasource
      version: "{{ version_simpod }}"
    - name: vertamedia-clickhouse-datasource
      version: "{{ version_clickhouse_datasource }}"
    - name: natel-discrete-panel
      version: "{{ version_natel_discrete_panel }}"
  notify: restart grafana
  register: grafana_plugin_install
  retries: 4
  delay: 2
  until: grafana_plugin_install is succeeded
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"
  tags:
    - requirements
