---
# have to be in migrate role because it's run once by default. and not in free strategy

- name: call consul to setup worker
  run_once: "True"
  include_role:
    name: consul
    tasks_from: service_config_update
  vars:
    consul_service_key: "noc/slots/worker/manifest"
    consul_service_internal_key: "Limit"
    consul_service_value: "{{ hostvars |json_query(\"*.noc_services[] | [?name=='worker'].{num:config.power} | sum([].num)\") }}"  # noqa 204
    consul_service_token: None
  tags:
    - worker

- name: call consul to setup metrics
  run_once: "True"
  include_role:
    name: consul
    tasks_from: service_config_update
  vars:
    consul_service_key: "noc/slots/metrics/manifest"
    consul_service_internal_key: "Limit"
    consul_service_value: "{{ hostvars |json_query(\"*.noc_services[] | [?name=='metrics'].{num:config.power} | sum([].num)\") }}"  # noqa 204
    consul_service_token: None
  tags:
    - metrics

- name: call consul to setup discovery
  run_once: "True"
  include_role:
    name: consul
    tasks_from: service_config_update
  vars:
    consul_service_key: "noc/slots/discovery-{{ item }}/manifest"
    consul_service_internal_key: "Limit"
    consul_service_value: "{{ hostvars | json_query(\"*.noc_services[] | [?name=='discovery'].{n:pool,num:config.power} | [?n=='\"+item+\"'] | sum([].num)\") }}"  # noqa 204
    consul_service_token: None
  with_items: "{{ hostvars |json_query('*.noc_services[] | [].pool') |unique }}"
  tags:
    - discovery

- name: call consul to setup ping
  run_once: "True"
  include_role:
    name: consul
    tasks_from: service_config_update
  vars:
    consul_service_key: "noc/slots/ping-{{ item }}/manifest"
    consul_service_internal_key: "Limit"
    consul_service_value: "{{ hostvars |json_query(\"*.noc_services[] | [?name=='ping'].{n:pool,num:config.power} | [?n=='\"+item+\"'] | sum([].num)\") }}"  # noqa 204
    consul_service_token: None
  with_items: "{{ hostvars |json_query('*.noc_services[] | [].pool') |unique }}"
  tags:
    - ping

- name: call consul to setup classifier
  run_once: "True"
  include_role:
    name: consul
    tasks_from: service_config_update
  vars:
    consul_service_key: "noc/slots/classifier-{{ item }}/manifest"
    consul_service_internal_key: "Limit"
    consul_service_value: "{{ hostvars |json_query(\"*.noc_services[] | [?name=='classifier'].{n:pool,num:config.power} | [?n=='\"+item+\"'] | sum([].num)\") }}"  # noqa 204
    consul_service_token: None
  with_items: "{{ hostvars |json_query('*.noc_services[] | [].pool') |unique }}"
  tags:
    - classifier

- name: call consul to setup correlator
  run_once: "True"
  include_role:
    name: consul
    tasks_from: service_config_update
  vars:
    consul_service_key: "noc/slots/correlator-{{ item }}/manifest"
    consul_service_internal_key: "Limit"
    consul_service_value: "{{ hostvars |json_query(\"*.noc_services[] | [?name=='correlator'].{n:pool,num:config.power} | [?n=='\"+item+\"'] | sum([].num)\") }}"  # noqa 204
    consul_service_token: None
  with_items: "{{ hostvars |json_query('*.noc_services[] | [].pool') |unique }}"
  tags:
    - correlator

- name: call consul to setup kafkasender
  run_once: "True"
  include_role:
    name: consul
    tasks_from: service_config_update
  vars:
    consul_service_key: "noc/slots/kafkasender/manifest"
    consul_service_internal_key: "Limit"
    consul_service_value: "{{ hostvars |json_query(\"*.noc_services[] | [?name=='kafkasender'].{num:config.power} | sum([].num)\") }}"  # noqa 204
    consul_service_token: None
  tags:
    - kafkasender
